language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
script:
  - coverage erase
  - coverage run -m unittest discover tests
  - coverage report
after_success:
  - coveralls
